import Foundation
import Trebuchet

struct FlyDeploymentProvider: DeploymentProvider {
    let id = "fly"

    func deploy(
        plan: DeploymentPlan,
        projectPath: String,
        executableProduct: String,
        verbose: Bool,
        terminal: Terminal
    ) async throws -> ProviderDeploymentResult {
        try checkFlyctl()

        let appName = resolvedAppName(plan: plan)
        let region = resolvedRegion(plan: plan)

        terminal.print("Preparing Fly.io deployment files...", style: .header)
        try writeFlyToml(appName: appName, region: region, to: projectPath)
        try writeDockerfile(product: executableProduct, to: projectPath)
        try writeDockerignore(to: projectPath)

        let appExists = try await checkAppExists(appName)
        if !appExists {
            terminal.print("Creating Fly.io app '\(appName)'...", style: .dim)
            try await createApp(appName, region: region, verbose: verbose)
        }

        terminal.print("Deploying to Fly.io...", style: .header)
        try await runFly(["deploy", "--app", appName], in: projectPath, verbose: verbose)

        let hostname = "\(appName).fly.dev"
        let deploymentInfo = FlyDeploymentInfo(
            projectName: plan.systemName,
            provider: "fly",
            appName: appName,
            hostname: hostname,
            region: region,
            databaseUrl: nil,
            deployedAt: Date()
        )

        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
        encoder.dateEncodingStrategy = .iso8601
        let infoData = try encoder.encode(deploymentInfo)

        return ProviderDeploymentResult(
            provider: id,
            summaryLines: [
                "App: \(appName)",
                "URL: https://\(hostname)",
                "Region: \(region)",
            ],
            deploymentInfo: infoData
        )
    }

    private func resolvedAppName(plan: DeploymentPlan) -> String {
        if let configured = plan.actors.compactMap({ $0.fly?.app }).first {
            return configured
        }

        let raw = plan.systemName
            .replacingOccurrences(of: " ", with: "-")
            .replacingOccurrences(of: "_", with: "-")
            .lowercased()

        return raw.filter { $0.isLetter || $0.isNumber || $0 == "-" }
    }

    private func resolvedRegion(plan: DeploymentPlan) -> String {
        if let configured = plan.actors.compactMap({ $0.fly?.region }).first {
            return configured
        }
        return "iad"
    }

    private func writeFlyToml(appName: String, region: String, to projectPath: String) throws {
        let contents = """
        # fly.toml - generated by Trebuchet deploy
        app = "\(appName)"
        primary_region = "\(region)"

        [build]
          dockerfile = "Dockerfile"

        [env]
          PORT = "8080"

        [http_service]
          internal_port = 8080
          force_https = true
          auto_stop_machines = "stop"
          auto_start_machines = true
          min_machines_running = 0
          processes = ["app"]

        [[vm]]
          memory = "1gb"
          cpu_kind = "shared"
          cpus = 1
        """

        try contents.write(toFile: "\(projectPath)/fly.toml", atomically: true, encoding: .utf8)
    }

    private func writeDockerfile(product: String, to projectPath: String) throws {
        let contents = """
        FROM swift:noble AS build

        RUN apt-get update && apt-get install -y --no-install-recommends libsqlite3-dev && rm -rf /var/lib/apt/lists/*
        WORKDIR /build
        COPY . .
        RUN swift build -c release --product \(product) --static-swift-stdlib -Xlinker -s

        FROM ubuntu:noble
        WORKDIR /app

        RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates libsqlite3-0 && rm -rf /var/lib/apt/lists/*

        COPY --from=build /build/.build/release/\(product) /app/server

        EXPOSE 8080

        ENTRYPOINT ["/app/server", "--_trebuchet-mode", "dev", "--_trebuchet-host", "0.0.0.0", "--_trebuchet-port", "8080"]
        """

        try contents.write(toFile: "\(projectPath)/Dockerfile", atomically: true, encoding: .utf8)
    }

    private func writeDockerignore(to projectPath: String) throws {
        let contents = """
        .build
        .git
        .swiftpm
        .DS_Store
        .trebuchet
        """

        try contents.write(toFile: "\(projectPath)/.dockerignore", atomically: true, encoding: .utf8)
    }

    private func checkFlyctl() throws {
        let process = Process()
        process.executableURL = URL(fileURLWithPath: "/usr/bin/env")
        process.arguments = ["which", "flyctl"]
        process.standardOutput = FileHandle.nullDevice
        process.standardError = FileHandle.nullDevice

        try process.run()
        process.waitUntilExit()

        guard process.terminationStatus == 0 else {
            throw CLIError.commandFailed("flyctl not found. Install with: brew install flyctl")
        }
    }

    private func checkAppExists(_ appName: String) async throws -> Bool {
        let process = Process()
        process.executableURL = URL(fileURLWithPath: "/usr/bin/env")
        process.arguments = ["flyctl", "apps", "list", "--json"]

        let pipe = Pipe()
        process.standardOutput = pipe
        process.standardError = FileHandle.nullDevice

        try process.run()
        process.waitUntilExit()

        guard process.terminationStatus == 0 else {
            return false
        }

        let data = pipe.fileHandleForReading.readDataToEndOfFile()
        guard let apps = try? JSONSerialization.jsonObject(with: data) as? [[String: Any]] else {
            return false
        }

        return apps.contains { ($0["Name"] as? String) == appName }
    }

    private func createApp(_ appName: String, region: String, verbose: Bool) async throws {
        _ = region
        let org = try await getCurrentOrg()
        try await runFly(["apps", "create", appName, "--org", org], in: ".", verbose: verbose)
    }

    private func getCurrentOrg() async throws -> String {
        let process = Process()
        process.executableURL = URL(fileURLWithPath: "/usr/bin/env")
        process.arguments = ["flyctl", "orgs", "list", "--json"]

        let pipe = Pipe()
        process.standardOutput = pipe
        process.standardError = FileHandle.nullDevice

        try process.run()
        process.waitUntilExit()

        guard process.terminationStatus == 0 else {
            throw CLIError.commandFailed("Failed to query Fly.io orgs. Run: flyctl auth login")
        }

        let data = pipe.fileHandleForReading.readDataToEndOfFile()
        guard let orgs = try? JSONSerialization.jsonObject(with: data) as? [String: String],
              let firstSlug = orgs.keys.first else {
            throw CLIError.commandFailed("No Fly.io organizations found.")
        }

        return orgs["personal"] != nil ? "personal" : firstSlug
    }

    private func runFly(_ args: [String], in directory: String, verbose: Bool) async throws {
        let process = Process()
        process.executableURL = URL(fileURLWithPath: "/usr/bin/env")
        process.arguments = ["flyctl"] + args
        process.currentDirectoryURL = URL(fileURLWithPath: directory)

        let stderrPipe = Pipe()
        process.standardError = stderrPipe

        if !verbose {
            process.standardOutput = FileHandle.nullDevice
        }

        try process.run()
        process.waitUntilExit()

        guard process.terminationStatus == 0 else {
            let errorData = stderrPipe.fileHandleForReading.readDataToEndOfFile()
            let message = String(data: errorData, encoding: .utf8)?.trimmingCharacters(in: .whitespacesAndNewlines) ?? ""
            throw CLIError.commandFailed("flyctl \(args.joined(separator: " ")) failed. \(message)")
        }
    }
}
