import ArgumentParser
import Foundation

struct DevCommand: AsyncParsableCommand {
    static let configuration = CommandConfiguration(
        commandName: "dev",
        abstract: "Run actors locally for development"
    )

    @Option(name: .shortAndLong, help: "Port to listen on")
    var port: UInt16 = 8080

    @Option(name: .shortAndLong, help: "Host to bind to")
    var host: String = "localhost"

    @Flag(name: .shortAndLong, help: "Enable verbose output")
    var verbose: Bool = false

    mutating func run() async throws {
        let terminal = Terminal()
        let cwd = FileManager.default.currentDirectoryPath

        terminal.print("")
        terminal.print("Starting local development server...", style: .header)
        terminal.print("")

        // Discover actors
        let discovery = ActorDiscovery()
        let actors = try discovery.discover(in: cwd)

        if actors.isEmpty {
            terminal.print("No distributed actors found.", style: .warning)
            throw ExitCode.failure
        }

        terminal.print("Found actors:", style: .info)
        for actor in actors {
            terminal.print("  • \(actor.name)", style: .dim)
        }
        terminal.print("")

        // Generate and run local bootstrap
        terminal.print("Building project...", style: .dim)

        let buildProcess = Process()
        buildProcess.executableURL = URL(fileURLWithPath: "/usr/bin/env")
        buildProcess.arguments = ["swift", "build"]
        buildProcess.currentDirectoryURL = URL(fileURLWithPath: cwd)

        if !verbose {
            buildProcess.standardOutput = FileHandle.nullDevice
            buildProcess.standardError = FileHandle.nullDevice
        }

        try buildProcess.run()
        buildProcess.waitUntilExit()

        guard buildProcess.terminationStatus == 0 else {
            terminal.print("Build failed.", style: .error)
            throw ExitCode.failure
        }

        terminal.print("✓ Build succeeded", style: .success)
        terminal.print("")

        // Start the local server
        terminal.print("Starting server on \(host):\(port)...", style: .info)
        terminal.print("Press Ctrl+C to stop.", style: .dim)
        terminal.print("")

        // Generate a simple local runner script
        let runnerScript = generateLocalRunner(actors: actors, host: host, port: port)
        let runnerPath = "\(cwd)/.trebuche/local_runner.swift"

        try FileManager.default.createDirectory(
            atPath: "\(cwd)/.trebuche",
            withIntermediateDirectories: true
        )
        try runnerScript.write(toFile: runnerPath, atomically: true, encoding: .utf8)

        terminal.print("Local development server started!", style: .success)
        terminal.print("")
        terminal.print("Endpoint: http://\(host):\(port)/invoke", style: .header)
        terminal.print("")

        // In a real implementation, this would start the actual server
        // For now, we'll just wait for Ctrl+C
        terminal.print("Note: Full local server implementation requires runtime integration.", style: .dim)
        terminal.print("Use 'swift run' with your project's actual entry point.", style: .dim)

        // Keep running until interrupted
        terminal.print("")
        terminal.print("Server ready. Press Ctrl+C to stop.", style: .info)

        // Use async sleep loop instead of semaphore
        while true {
            try await Task.sleep(for: .seconds(60))
        }
    }

    private func generateLocalRunner(actors: [ActorMetadata], host: String, port: UInt16) -> String {
        var actorRegistrations = ""
        for actor in actors {
            actorRegistrations += """
                let \(actor.name.lowercased()) = \(actor.name)(actorSystem: gateway.system)
                try await gateway.expose(\(actor.name.lowercased()), as: "\(actor.name.lowercased())")
                print("  Exposed: \(actor.name)")

            """
        }

        return """
        // Auto-generated local development runner
        // Generated by trebuche dev

        import Foundation
        import Trebuche
        import TrebucheCloud

        @main
        struct LocalRunner {
            static func main() async throws {
                print("Starting local development server...")

                let gateway = CloudGateway.development(
                    host: "\(host)",
                    port: \(port)
                )

                // Register actors
        \(actorRegistrations)

                print("Server running on http://\(host):\(port)")
                print("Press Ctrl+C to stop")

                try await gateway.run()
            }
        }
        """
    }
}
